### ISSUE TITLE
Report the balance of validators

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/cron-jobs#48]
Make a script that sends a report when the balance of accounts are out of range.
And I think it's good if it sends a report daily.

**Comment by sgkim126** [comment]
I created the wiki that has links to the explorer.
But checking it manually is annoying.
Please write the script that reports daily.
https://github.com/kodebox-io/kodebox-internal/wiki/Accounts-for-mainnet

**Comment by HoOngEe** [comment]
@sgkim126 What's the meaning of "balance is out of range" here? Larger than the total supply?

**Comment by sgkim126** [comment]
@HoOngEe I want the script receives the minimum and maximum balance and sends a message if the balance of the accounts is out of range.

**Comment by HoOngEe** [comment]
@sgkim126 Ok, thanks.
