### ISSUE TITLE
Monitor indexer status

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/cron-jobs#50]

**Comment by sgkim126** [comment]
@majecty Would you do it?
I think we can add this feature on the monitor.

**Comment by majecty** [comment]
Okay. I'll do this.

**Comment by majecty** [comment]
I'll add these alarms
1. Send ping
Send ping to an indexer every 5 minutes, If the indexer doesn't respond, then send an alarm message.

2. Check Indexed block number
Check the indexed block number every 10 minutes. If the number is not changed in 10 minutes, send an alarm.

3. Send a status message every day.
Send the current indexed block number everyday morning.

**Comment by majecty** [comment]
Resolved by #258
